### ISSUE TITLE
IPC server doesn't accept "single" C descriptor in request

### ISSUE THREAD

**Issue by misson20000** [Atmosphere-NX/Atmosphere-libs#18]
The GetFirmwareVersion command (`set:sys#3`) is reimplemented in ams_mitm. It has a single buffer, with `Out | HipcPointer | FixedSize` flags. If a client calls this command and passes a "single" C descriptor (flags = 2) in the request, the server will close the session. Nintendo servers will accept this usage and correctly write the data back to the single pointer buffer.

Unknown whether the issue generalizes to buffers with other flags and comes from the fact that the "single" C descriptor exists at all in the request or whether it does not and the issue is that this specific buffer type will not write back to "single" C descriptor.

Example command buffer:
```
04 00 00 00 08 08 00 00  00 00 00 00 00 00 00 00  |  ................
53 46 43 49 00 00 00 00  03 00 00 00 00 00 00 00  |  SFCI............
00 00 00 00 00 00 00 00  60 6c 66 4c 07 00 00 01  |  ........`lfL....
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |  ................
```

**Comment by SciresM** [comment]
Fixed in atmosphere-master, will be pushed in next subrepo push.
