### ISSUE TITLE
[Suggestion] Add BoostApplicationMemoryResourceLimit to pm

### ISSUE THREAD

**Issue by masagrator** [Atmosphere-NX/Atmosphere-libs#20]
### What feature are you suggesting?
Add `BoostApplicationMemoryResourceLimit`, based on `Result BoostSystemMemoryResourceLimit(u64 boost_size)` from pm_resource_manager in Atmosphere repo and option to bring back default memory values for Applet and Application

#### Overview:
- Function that can give additional memory resource for Application at the cost of Applet memory</br>

#### Smaller Details: 
- There is an option already available in Atmosphere code, but for System that takes its part from Application resource. New function will need to rewrite OG function to take Applet memory and give it to Application.</br>

#### Nature of Request:  
- Addition
  - based on Atmosphere [ams::pm::resource::BoostSystemMemoryResourceLimit(u64 boost_size)](https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/pm/source/impl/pm_resource_manager.cpp#L283)

### What component do you feel this would best fit within?
- libstratosphere/PM

### Why would this feature be useful?
Some games are very fragile if they can't take all memory they want, so in some cases code injection results in crashes or glitches. This will help by temporarily rising available resources, so it won't get in the way of games.

I took template from Atmosphere repo to better categorize my thoughts.
Sorry this isn't Pull Request, but I failed at making anything that can compile.

**Comment by masagrator** [comment]
Ok, I got deeper in this and I see this is not simple. Closing and waiting until kernel will be reimplemented. ;)

**Comment by SciresM** [comment]
Heh, yeah. You came to the same conclusion I came to ^^
