### ISSUE TITLE
Building issue, file missing

### ISSUE THREAD

**Issue by Near2018** [Atmosphere-NX/Atmosphere-libs#23]
Hi! Building everything else works fine but when I try to build stratosphere, I get this error:

In file included from C:/Users/Giuseppe/Desktop/Atmosphere-libs-master/Atmosphere-libs-master/libstratosphere/source/capsrv/server/jpeg/decodersrv_software_jpeg_decoder.cpp:18:
C:/Users/Giuseppe/Desktop/Atmosphere-libs-master/Atmosphere-libs-master/libstratosphere/source/capsrv/server/jpeg/capsrv_server_jpeg_library_types.hpp:19:10: fatal error: jpeglib.h: No such file or directory
   19 | #include <jpeglib.h>

Is there a way to fix this?

**Comment by HookedBehemoth** [comment]
Install libjpeg-turbo from devkitpro's pacman

**Comment by Near2018** [comment]
Thanks! Do you know a video or text tutorial on how to do that?

**Comment by TheExpertNoob** [comment]
> Thanks! Do you know a video or text tutorial on how to do that?

sudo dkp-pacman -S switch-libjpeg-turbo

**Comment by impeeza** [comment]
this issue still happen?

**Comment by SciresM** [comment]
no.

**Comment by impeeza** [comment]
Thank you
