### ISSUE TITLE
Compilation atmosphere-libs pm library

### ISSUE THREAD

**Issue by dogty** [Atmosphere-NX/Atmosphere-libs#24]
Hi
When I try to compile the stratosphere lib I get a compilation error ::PmResourceLimitValues has not been declared (file pm_info_api.cpp:32:67).

I have also noticed in the code that the function pminfoGetAppletCurrentResourceLimitValues doesn't exist but is used in the pm_info_api.cpp file. Do I have to install a particular library?

Sorry if this isn't the place where to post these kind of issues.

Best regards

**Comment by SciresM** [comment]
You need to include the PR I made for 14.0.0 support to libnx, which hasn't been merged yet.

There isn't really a right place for these issues. I recommend just pinging me on discord.
