### ISSUE TITLE
libstratosphere undeclared ::svcMapInsecureMemory and ::svcUnmapInsecureMemory

### ISSUE THREAD

**Issue by urherenow** [Atmosphere-NX/Atmosphere-libs#26]
Atmosphere/libraries/libstratosphere/include/stratosphere/svc/svc_stratosphere_shims.hpp:507:32: error: '::svcMapInsecureMemory' has not been declared; did you mean 'MapInsecureMemory'?
  507 |                     R_RETURN(::svcMapInsecureMemory(reinterpret_cast<void *>(static_cast<uintptr_t>(address)), size));
      |                                ^~~~~~~~~~~~~~~~~~~~
/Atmosphere/libraries/config//../libvapours/include/vapours/results/results_common.hpp:436:48: note: in definition of macro 'R_RETURN'
  436 |         const ::ams::Result _tmp_r_throw_rc = (res_expr);                                                                                      \
      |                                                ^~~~~~~~
/Atmosphere/libraries/libstratosphere/include/stratosphere/svc/svc_stratosphere_shims.hpp: In function 'ams::Result ams::svc::aarch64::lp64::UnmapInsecureMemory(ams::svc::Address, ams::svc::Size)':
/Atmosphere/libraries/libstratosphere/include/stratosphere/svc/svc_stratosphere_shims.hpp:511:32: error: '::svcUnmapInsecureMemory' has not been declared; did you mean 'UnmapInsecureMemory'?
  511 |                     R_RETURN(::svcUnmapInsecureMemory(reinterpret_cast<void *>(static_cast<uintptr_t>(address)), size));
      |                                ^~~~~~~~~~~~~~~~~~~~~~

dkp is up to date, and I built libnx from current source for good measure.

**Comment by SciresM** [comment]
You need to include the PR I made for 15.0.0 support to libnx, which hasn't been merged yet. Install it locally, or wait a few days for it to be merged. Atmosphere often requires in-progress PRs after major system updates.

There isn't really a right place for these issues. I recommend just pinging me on discord.
