### ISSUE TITLE
Add API to reload LayeredFS path cache

### ISSUE THREAD

**Issue by gtiersma** [Atmosphere-NX/Atmosphere-libs#29]
When using an app that runs asynchronously to a launched game (such as a Tesla overlay), if the app were to add or remove mod files from `atmosphere/contents/[ RUNNING GAME TITLE ID ]`, the game will not load any of the changed mod files until the game is relaunched.

As I understand it, LayeredFS caches all the file paths that are located in the game's directory on game launch, but it never updates the cache again while the game is running.

**Proposal:**

Add an API method that could be called from an atmosphere library to trigger LayeredFS to reload its file path cache for the currently running game. Apps could call this method after any updates are performed to the game's directory.

Then (I imagine) the next time the game reaches a point where it needs to load a file into memory, the "latest" file will be loaded.

---

Not sure how feasible such a feature is since I'm unfamiliar with the internal workings of LayeredFS, but if it can be done, it could be really helpful for certain apps.

**Comment by SciresM** [comment]
No, this is fundamentally incompatible with the constraints on layeredfs, namely that games read and cache the file metadata tables immediately, which requires a one-time processing of all files as soon as romfs is first requested, and which cannot be changed without game code patches.

Just close and re-open the game. Do not change game mod files while a game is open; this can have weird effects, including causing atmosphere crashes. It's not supported or even supportable.

**Comment by gtiersma** [comment]
Thanks. Appreciate the quick explanation
